---
apiVersion: v1

kind: ServiceAccount
metadata:
    name: gitlab-service-account
---

# Create Gitlab service account to deploy to Kubernetes
# i.e. AWS EKS from Gitlab.
# Run with 'kubectl apply -f gitlab-service-account.yaml'

apiVersion: rbac.authorization.k8s.io/v1beta1

kind: ClusterRoleBinding
metadata:
    name: gitlab-service-account-role-binding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: gitlab-service-account
      namespace: default
